springdoc:
  api-docs:
    path: /api-docs

spring:
  sql:
    init:
      platform: h2
      mode: always
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: product_user
    password:
  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      #Set ddl-auto to none as we're handling inputting the data for this service.
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    #https://www.baeldung.com/spring-boot-data-sql-and-schema-sql
    defer-datasource-initialization: true
