#Get Spring to set a random port number on boot up.
#https://www.javacodemonk.com/setting-a-random-port-in-spring-boot-application-at-startup-87022e01
server:
  port: 0

#Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG