
spring:
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:mem:db1
    driver: org.h2.Driver

    jpa:
      hibernate:
        ddl-auto: none

h2:
  console:
    enabled: true
    path: h2-console